version: '3.1'

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: mysql_db
    ports:
      - "3306:3306"
    tty: true

  adminer:
    image: adminer
    ports:
      - "8082:8080"

  app:
    build:
      context: ./Backend
    volumes:
      - "./Backend:/go"
    container_name: golang_app
    links:
      - "mysqldb:database"
    environment:
      MYSQL_IP: mysqldb
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - mysqldb
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbit
    ports:
       - "5672:5672"
       - "15672:15672"
    tty: true

webapp:
  image: nginx
  volumes:
    - ./templates:/etc/nginx/templates
  ports:
    - "8080:80"
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80